{% set name = "pysimplevalidate" %}
{% set version = "0.2.12" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/0b/54/8fd99436073dbdbba719e08e1b7e5f3f36a8cc9e518612e1b97e4806d2ce/PySimpleValidate-0.2.12.tar.gz"
  sha256: 645d24bdca17ad4c40658f3aa0bd5c1aa1688ba0c02ba75c5ed2cb3b8abaaa19

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
    - typing
  run:
    - python
    - typing

test:
  imports:
    - pysimplevalidate

about:
  home: "https://github.com/asweigart/pysimplevalidate"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "A collection of string-based validation functions, suitable for use in other Python 2 and 3 applications."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
