package:
  name: sclogging
  version: 1.0.8

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . --ignore-requires-python

source:
  url: https://files.pythonhosted.org/packages/42/f1/1d86ee963808c7b50da7193a8c6bd2b6d0d7112519c4367fe5eb06803441/sclogging-1.0.8.tar.gz
  sha256: 7834e76d2f9989508bb678f3bf3ca842e562c6b28d3023e6adffcee6e6c6941e
  md5: f3921d38962372698896f2680d3888f1

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - sclogging

about:
  summary: 'A Python module (with the help of coloredlogs) to add color to logs.'
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/sshimek42/sclogging
  doc_url: https://sclogging.readthedocs.io/