logging_log_to_file = false
logging_path = "C:\\Logs"
logging_level = "INFO"
logging_file_level = "WARNING"
logging_ext = "log"
logging_auto_create_dir = true
spacer = "_"
spacer_color = "LIGHTBLACK_EX"

[specific_loggers]
urllib3 = "WARNING"
selenium = "WARNING"
xhtml2pdf = "WARNING"
