logging_path = 'C:\Logs'
logging_level = 'WARNING'
logging_file_level = 'WARNING'
logging_ext = 'log'
logging_auto_create_dir = false
logging_log_to_file = false
spacer = '='
spacer_color = 'LIGHTBLACK_EX'
specific_loggers = {urllib3 = 'WARNING', selenium = 'WARNING', xhtml2pdf = 'WARNING'}